name: McStasScript unit tests on Linux
on: [push]
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
              
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
                  
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
              
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install pytest
          
      - name: Show file structure
        if: ${{ matrix.os }} == "ubuntu-latest" || ${{ matrix.os }} == "windows-latest"
        run: tree .
        
      - name: Show file structure
        if: ${{ matrix.os }} == "macos-latest"
        run: find .

      - name: Run unit tests
        run: python -m pytest mcstasscript/tests/
