name: McStasScript unit tests on OS X
on: [push]
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    runs-on: macos-latest
      
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
              
      - name: Install dependencies (libpyvinyl)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install pytest
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ env.BRANCH }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install pytest
        
      - name: Show file structure
        run: find .

      - name: Run unit tests
        run: python -m pytest mcstasscript/tests/
